-- +goose Up
-- +goose StatementBegin
CREATE TABLE questions (
  id bigint PRIMARY KEY generated by DEFAULT as identity,
  assessment_id bigint NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  test_case JSONB,
  language VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
  updated_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
  deleted_at TIMESTAMP DEFAULT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE questions;
-- +goose StatementEnd
