-- +goose Up
-- +goose StatementBegin
CREATE TABLE candidates (
  id bigint PRIMARY KEY generated by DEFAULT as identity,
  organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  phone VARCHAR(255) NOT NULL UNIQUE,
  phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
  no_dual_screen BOOLEAN NOT NULL DEFAULT FALSE,
  camera BOOLEAN NOT NULL DEFAULT FALSE,
  microphone BOOLEAN NOT NULL DEFAULT FALSE,
  looked_outside_ai INTEGER NOT NULL DEFAULT 0,
  resume_url VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
  updated_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
  deleted_at TIMESTAMP DEFAULT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE candidates;
-- +goose StatementEnd
