-- +goose Up
-- +goose StatementBegin
CREATE TABLE assessment_submissions (
  id bigint PRIMARY KEY generated by DEFAULT as identity,
  candidate_id bigint NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  recording_url VARCHAR(255),
  status VARCHAR(255) NOT NULL,
  answer TEXT,
  result BOOLEAN NOT NULL,
  number_of_code_runs INTEGER NOT NULL DEFAULT 0,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP,
  duration INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
  updated_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
  deleted_at TIMESTAMP DEFAULT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE assessment_submissions;
-- +goose StatementEnd
