-- +goose Up
-- +goose StatementBegin
CREATE TABLE assessments (
  id bigint PRIMARY KEY generated by DEFAULT as identity,
  organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  job_name VARCHAR(255) NOT NULL,
  unique_hash VARCHAR(255) NOT NULL UNIQUE,
  score INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
  updated_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
  deleted_at TIMESTAMP DEFAULT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE assessments;
-- +goose StatementEnd
