-- +goose Up
-- +goose StatementBegin
CREATE TABLE organizations (
  id bigint PRIMARY KEY generated by DEFAULT as identity,
  name VARCHAR(255) NOT NULL,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  about TEXT,
  logo_url VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
  updated_at TIMESTAMP NOT NULL DEFAULT (now() at time zone 'utc'),
  deleted_at TIMESTAMP DEFAULT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE organizations;
-- +goose StatementEnd
